// include yumpu sdk
var yumpu = require('../yumpu');
// make an instance of the Yumpu sdk class;
var y = new yumpu();

 /**
  * @api {get} /document.json getDocument()
  * @apiVersion 1.0.0
  * @apiName Document get
  * @apiGroup Document
  *
  * @apiHeaderExample {js} Java-Script-Example:
  *  var yumpu = require('yumpu.js');
  *  var parameters = {
  *     id: 20327033
  *  };
  *  yumpu.getDocument(parameters, function(statusCode, document){
  *     console.log('Status: ' + statusCode);
  *     console.log(document);
  *  });
  *
  * @apiParam {Integer} id One of your document ids
  * @apiParam {String} [return_fields] Customize the responses by setting the return fields (id, create_date, update_date, url, short_url, image_small, image_medium, image_big, language, title, description, tags, embed_code, settings).
       <br/><br/><b>Default:</b> id, url, short_url, image_small, image_medium, image_big, language, title, description, tags, embed_code
  *
  * @apiSuccessExample Success-Response:
  *     HTTP/1.1 200 OK
  *       {
  *         "document": [
  *           {
  *             "id": "20327033",
  *             "image": {
  *               "big": "http://images001.yumpu.com/yumpu.com/000/020/459/910/1379668843_8906/zoom/TOUROPA_AllgaeuKleinwalse000001.jpg"
  *             }
  *           }
  *         ],
  *         "state": "success"
  *       }
  */
var parameters = {
    id: 10672,
    return_fields: 'id,url,create_date,update_date,url,image_small'
};
// y.getDocument(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });



  /**
   * @api {post} /document.json postDocumentFile()
   * @apiVersion 1.0.0
   * @apiName Document post
   * @apiGroup Document
   *
   * @apiHeaderExample {js} Java-Script-Example:
   *  var yumpu = require('yumpu.js');
   *  var parameters = {
   *     title: 'My document title',
   *     file: './example/media/yumpu.pdf'
   *  };
   *  yumpu.postDocumentFile(parameters, function(statusCode, document){
   *     console.log('Status: ' + statusCode);
   *     console.log(document);
   *  });
   *
   * @apiParam {Integer} file File data
   * @apiParam {String} title A title for your document. Min. length 5 characters, max. length 255 characters
   * @apiParam {String} [description] A description for your document. Min. length 5 characters, max. length 2500 characters
   * @apiParam {String} [category] 1, 2 or … (A list of valid category ids: Document categories)
      <br/><br/><b>Default:</b> 0 = None
   * @apiParam {String} [language] en, de or … (A list of valid languages: Document languages)
      <br/><br/><b>Default:</b> en
   * @apiParam {String} [tags] A list of words seperated by comma (house,garden,balcony). Min. length 3 characters, max. length 30 characters. Allowed characters a-z and a space.
      <br/><br/><b>Default:</b> Autogenerated by tag service
   * @apiParam {String} [visibility] public, private, rprotected, pprotected, dprotected, webkiosk, appkiosk or webappkiosk (rprotected = protected by referrer, pprotected = protected by password, dprotected = protected by domain(s))
      <br/><br/><b>Default:</b> public
   * @apiParam {String} [domains] A list of domains seperated by a comma (Note: Visibility must be set to dprotected)
      <br/><br/><b>Examples:</b>
      <br/>yumpu.com,blog.yumpu.com,developers.yumpu.com
      <br/>yumpu.com
   *
   *
   * @apiSuccessExample Success-Response:
   *     HTTP/1.1 200 OK
   *       {
   *          "file": {
   *            "client_name": "yumpu.pdf",
   *            "server_name": "812373127ee7a372a5130f9096545b5e524940f77e4d06.24583099.pdf",
   *            "size": "23.1 MB",
   *            "mime_type": "application/pdf",
   *            "sha1_checksum": "d5666133b4a909a6506aeb09d57956a12a97e0e4"
   *          },
   *          "document": {
   *            "title": "My document title"
   *          },
   *          "progress_id": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
   *          "state": "success"
   *        }
   *
   */
var parameters = {
    title: 'MyDocument',
    file: './example/media/yumpu.pdf'
};
// y.postDocumentFile(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });

// document post url example with page_teaser_image
// more details on : http://developers.yumpu.com/api/document/post-url/
var parameters = {
    'title': 'Sieggggggg',
    'url': 'https://s3-eu-west-1.amazonaws.com/yumpu/api/yumpu_sdk_example_pdf.pdf',
    'page_teaser_image': __dirname + '/media/yumpu.png',
    'page_teaser_page_range': '1-1',
    'page_teaser_url': 'http://www.yumpu.com/en'
        // write optional parameters here
};
// y.postDocumentUrl(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });

// document post url example without page_teaser_image
// more details on : http://developers.yumpu.com/api/document/post-url/
var parameters = {
    'title': 'Sieggggggg',
    'url': 'http://www.pdf995.com/samples/pdf.pdf',
    'description': 'Thats my description'
        // write optional parameters here
};
y.postDocumentUrl(parameters, function(statusCode, document){
  console.log('Status: ' + statusCode)
  console.log(document);
});



/**
 * @api {delete} /document.json deleteDocument()
 * @apiVersion 1.0.0
 * @apiName Document delete
 * @apiGroup Document
 *
 *
 * @apiHeaderExample {js} Java-Script-Example:
 *  var yumpu = require('yumpu.js');
 *  var parameters = '{
 *    id: 20327033
 *  }';
 *  yumpu.deleteDocument(parameters, function(statusCode, document){
 *     console.log('Status: ' + statusCode);
 *     console.log(document);
 *  });
 *
 * @apiParam {Integer} id One of your document ids
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *    {"state":"success"}
 *
 */
var parameters = {
    id: 10672
  };
// y.deleteDocument(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });
