// include yumpu sdk
var yumpu = require('../yumpu');
// make an instance of the Yumpu sdk class;
var y = new yumpu();

 /**
  * @api {get} http://api.yumpu.com/2.0/document.json getDocument()
  * @apiVersion 1.0.0
  * @apiName Document get
  * @apiGroup Document
  *
  * @apiHeaderExample {js} Java-Script-Example:
  *  var yumpu = require('yumpu.js');
  *  var parameters = {
  *     id: 20327033
  *  };
  *  yumpu.getDocument(parameters, function(statusCode, document){
  *     console.log('Status: ' + statusCode);
  *     console.log(document);
  *  });
  *
  * @apiParam {Integer} id One of your document ids
  * @apiParam {String} [return_fields] Customize the responses by setting the return fields (id, create_date, update_date, url, short_url, image_small, image_medium, image_big, language, title, description, tags, embed_code, settings).
       <br/><br/><b>Default:</b> id, url, short_url, image_small, image_medium, image_big, language, title, description, tags, embed_code
  *
  * @apiSuccessExample Success-Response:
  *     HTTP/1.1 200 OK
  *       {
  *         "document": [
  *           {
  *             "id": "20327033",
  *             "image": {
  *               "big": "http://images001.yumpu.com/yumpu.com/000/020/459/910/1379668843_8906/zoom/TOUROPA_AllgaeuKleinwalse000001.jpg"
  *             }
  *           }
  *         ],
  *         "state": "success"
  *       }
  */
var parameters = {
    id: '55886815',
    return_fields: 'id,url,create_date,update_date,url,image_small'
};
y.getDocument(parameters, function(statusCode, document) {
    console.log('Status: ' + statusCode)
    console.log(document);
});



/**
 * @api {post} http://api.yumpu.com/2.0/document/file.json postDocumentFile()
 * @apiVersion 1.0.0
 * @apiName Document post file
 * @apiGroup Document
 *
 * @apiHeaderExample {js} Java-Script-Example:
 *  var yumpu = require('yumpu.js');
 *  var parameters = {
 *     title: 'My document title',
 *     file: './example/media/yumpu.pdf'
 *  };
 *  yumpu.postDocumentFile(parameters, function(statusCode, document){
 *     console.log('Status: ' + statusCode);
 *     console.log(document);
 *  });
 *
 * @apiParam {Integer} file File data
 * @apiParam {String} title A title for your document. Min. length 5 characters, max. length 255 characters
 * @apiParam {String} [description] A description for your document. Min. length 5 characters, max. length 2500 characters
 * @apiParam {String} [category] 1, 2 or … (A list of valid category ids: Document categories)
    <br/><br/><b>Default:</b> 0 = None
 * @apiParam {String} [language] en, de or … (A list of valid languages: Document languages)
    <br/><br/><b>Default:</b> en
 * @apiParam {String} [tags] A list of words seperated by comma (house,garden,balcony). Min. length 3 characters, max. length 30 characters. Allowed characters a-z and a space.
    <br/><br/><b>Default:</b> Autogenerated by tag service
 * @apiParam {String} [visibility] public, private, rprotected, pprotected, dprotected, webkiosk, appkiosk or webappkiosk (rprotected = protected by referrer, pprotected = protected by password, dprotected = protected by domain(s))
    <br/><br/><b>Default:</b> public
 * @apiParam {String} [domains] A list of domains seperated by a comma (Note: Visibility must be set to dprotected)
    <br/><br/><b>Examples:</b>
    <br/>yumpu.com,blog.yumpu.com,developers.yumpu.com
    <br/>yumpu.com
 * @apiParam {String} [validity] 	Valid from and / or valid until
    <br/><br/><b>Examples:</b>
    <br/>2013-10-01T00:00:00-2013-10-30T23:59:59 (valid from 2013-10-01 00:00:00, valid until 2013-10-30 23:59:59)
    <br/>2013-10-01T00:00:00- (valid from 2013-10-01 00:00:00-)
    </br>-2013-10-30T23:59:59 (valid until -2013-10-30 23:59:59)
 * @apiParam {String} [blurred] 	Page numbers seperated by comma.
    <br/><br/><b>Examples:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_image] Image data
    <br/>The image must be less than 2 MB in size.
    <br/>Allowed mime types are image/gif, image/jpeg, image/pjpeg, image/png and image/x-png.
    <br/>The image will be resized to fit in the page dimensions (of your magazine).
    <br/><br/><b>Note:</b> If you use page_teaser_image, the parameters page_teaser_page_range and page_teaser_url are required.
 * @apiParam {String} [page_teaser_page_range] Page numbers seperated by comma.
    <br/><br/><b>Example:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_page_range] A valid URL.
    <br/><br/><b>Example:</b> http://www.yumpu.com/en
 * @apiParam {String} [downloadable] Allow users to download your source pdf file. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [detect_elements] Detect elements automatically? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [recommended_magazines] Show recommended magazines on Yumpu? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [social_sharing] Show social sharing buttons on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_social_sharing] Show social sharing buttons in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_download_pdf] Show button „download pdf“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_print_page] Show button „print page“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_branding] Show Yumpu branding in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_sidebar] Show a list of recommended documents in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_html5_c2r]	Activate HTML5 full screen on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_outer_shadow] Drop shadow in Yumpu player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_inner_shadow] Shadow effects on pages. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_ga] Activate Google Analytics tracking. A valid UA code from Google Analytics.
 * @apiParam {String} [access_tags] One or multiple access_tag ids (myid1 or myid1,myid2)
 * @apiParam {String} [subscriptions] One or multiple subscription ids (myid1 or myid1,myid2)
 * @apiParam {String} [iap] Enable In-App Purchase (y or n)
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [itc_product_id] iTunes Product ID
 *
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
 *        "file": {
 *          "client_name": "yumpu.pdf",
 *          "server_name": "812373127ee7a372a5130f9096545b5e524940f77e4d06.24583099.pdf",
 *          "size": "23.1 MB",
 *          "mime_type": "application/pdf",
 *          "sha1_checksum": "d5666133b4a909a6506aeb09d57956a12a97e0e4"
 *        },
 *        "document": {
 *          "title": "My document title"
 *        },
 *        "progress_id": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
 *        "state": "success"
 *      }
 *
 */
var parameters = {
    title: 'MyDocument',
    file: './example/media/yumpu.pdf',
    page_teaser_image: './example/media/yumpu.png',
    page_teaser_page_range: '1-1',
    page_teaser_url: 'http://www.yumpu.com/en'
};
// y.postDocumentFile(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });

// document post url example with page_teaser_image
// more details on : http://developers.yumpu.com/api/document/post-url/
var parameters = {
    'title': 'Sieggggggg',
    'url': 'http://www.pdf995.com/samples/pdf.pdf',
    'page_teaser_image': './example/media/yumpu.png',
    'page_teaser_page_range': '1-1',
    'page_teaser_url': 'http://www.yumpu.com/en'
};
// y.postDocumentUrl(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });

/**
 * @api {post} http://api.yumpu.com/2.0/document/url.json postDocumentUrl()
 * @apiVersion 1.0.0
 * @apiName Document post url
 * @apiGroup Document
 *
 * @apiHeaderExample {js} Java-Script-Example:
 *  var yumpu = require('yumpu.js');
 *  var parameters = {
 *     title: 'My document title',
 *     url: 'http://www.domain.com/filename.pdf'
 *  };
 *  yumpu.postDocumentFile(parameters, function(statusCode, document){
 *     console.log('Status: ' + statusCode);
 *     console.log(document);
 *  });
 *
 * @apiParam {Integer} url URL of document to be uploaded (public accessable). Allowed content types application/pdf or application/octet-stream. Max. file size is 100 MB.
 * @apiParam {String} title A title for your document. Min. length 5 characters, max. length 255 characters
 * @apiParam {String} [description] A description for your document. Min. length 5 characters, max. length 2500 characters
 * @apiParam {String} [category] 1, 2 or … (A list of valid category ids: Document categories)
    <br/><br/><b>Default:</b> 0 = None
 * @apiParam {String} [language] en, de or … (A list of valid languages: Document languages)
    <br/><br/><b>Default:</b> en
 * @apiParam {String} [tags] A list of words seperated by comma (house,garden,balcony). Min. length 3 characters, max. length 30 characters. Allowed characters a-z and a space.
    <br/><br/><b>Default:</b> Autogenerated by tag service
 * @apiParam {String} [visibility] public, private, rprotected, pprotected, dprotected, webkiosk, appkiosk or webappkiosk (rprotected = protected by referrer, pprotected = protected by password, dprotected = protected by domain(s))
    <br/><br/><b>Default:</b> public
 * @apiParam {String} [domains] A list of domains seperated by a comma (Note: Visibility must be set to dprotected)
    <br/><br/><b>Examples:</b>
    <br/>yumpu.com,blog.yumpu.com,developers.yumpu.com
    <br/>yumpu.com
 * @apiParam {String} [validity] 	Valid from and / or valid until
    <br/><br/><b>Examples:</b>
    <br/>2013-10-01T00:00:00-2013-10-30T23:59:59 (valid from 2013-10-01 00:00:00, valid until 2013-10-30 23:59:59)
    <br/>2013-10-01T00:00:00- (valid from 2013-10-01 00:00:00-)
    </br>-2013-10-30T23:59:59 (valid until -2013-10-30 23:59:59)
 * @apiParam {String} [blurred] 	Page numbers seperated by comma.
    <br/><br/><b>Examples:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_image] Image data
    <br/>The image must be less than 2 MB in size.
    <br/>Allowed mime types are image/gif, image/jpeg, image/pjpeg, image/png and image/x-png.
    <br/>The image will be resized to fit in the page dimensions (of your magazine).
    <br/><br/><b>Note:</b> If you use page_teaser_image, the parameters page_teaser_page_range and page_teaser_url are required.
 * @apiParam {String} [page_teaser_page_range] Page numbers seperated by comma.
    <br/><br/><b>Example:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_page_range] A valid URL.
    <br/><br/><b>Example:</b> http://www.yumpu.com/en
 * @apiParam {String} [downloadable] Allow users to download your source pdf file. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [detect_elements] Detect elements automatically? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [recommended_magazines] Show recommended magazines on Yumpu? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [social_sharing] Show social sharing buttons on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_social_sharing] Show social sharing buttons in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_download_pdf] Show button „download pdf“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_print_page] Show button „print page“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_branding] Show Yumpu branding in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_sidebar] Show a list of recommended documents in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_html5_c2r]	Activate HTML5 full screen on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_outer_shadow] Drop shadow in Yumpu player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_inner_shadow] Shadow effects on pages. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_ga] Activate Google Analytics tracking. A valid UA code from Google Analytics.
 * @apiParam {String} [access_tags] One or multiple access_tag ids (myid1 or myid1,myid2)
 * @apiParam {String} [subscriptions] One or multiple subscription ids (myid1 or myid1,myid2)
 * @apiParam {String} [iap] Enable In-App Purchase (y or n)
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [itc_product_id] iTunes Product ID
 *
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
      "file": {
        "url": "http:\/\/www.domain.com\/filename.pdf",
        "client_name": "filename.pdf",
        "size": "889.5 KB",
        "mime_type": "application\/pdf"
      },
      "document": {
        "url": "http:\/\/www.domain.com\/filename.pdf",
        "title": "My document title"
      },
      "progress_id": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
      "state": "success"
    }
 *
 */
var parameters = {
    'title': 'Sieggggggg',
    'url': 'http://www.pdf995.com/samples/pdf.pdf',
    'description': 'Thats my description'
        // write optional parameters here
};
// y.postDocumentUrl(parameters, function(statusCode, document){
//   console.log('Status: ' + statusCode)
//   console.log(document);
// });

/**
 * @api {put} http://api.yumpu.com/2.0/document.json putDocument()
 * @apiVersion 1.0.0
 * @apiName Document put
 * @apiGroup Document
 *
 * @apiHeaderExample {js} Java-Script-Example:
 *  var yumpu = require('yumpu.js');
 *  var parameters = {
 *    id: '20582984',
 *    title: 'My new document title'
 *  };
 *  yumpu.putDocumentFile(parameters, function(statusCode, document){
 *     console.log('Status: ' + statusCode);
 *     console.log(document);
 *  });
 *
 * @apiParam {Integer} id One of your document ids
 * @apiParam {String} title A title for your document. Min. length 5 characters, max. length 255 characters
 * @apiParam {String} [description] A description for your document. Min. length 5 characters, max. length 2500 characters
 * @apiParam {String} [category] 1, 2 or … (A list of valid category ids: Document categories)
    <br/><br/><b>Default:</b> 0 = None
 * @apiParam {String} [language] en, de or … (A list of valid languages: Document languages)
    <br/><br/><b>Default:</b> en
 * @apiParam {String} [tags] A list of words seperated by comma (house,garden,balcony). Min. length 3 characters, max. length 30 characters. Allowed characters a-z and a space.
    <br/><br/><b>Default:</b> Autogenerated by tag service
 * @apiParam {String} [visibility] public, private, rprotected, pprotected, dprotected, webkiosk, appkiosk or webappkiosk (rprotected = protected by referrer, pprotected = protected by password, dprotected = protected by domain(s))
    <br/><br/><b>Default:</b> public
 * @apiParam {String} [domains] A list of domains seperated by a comma (Note: Visibility must be set to dprotected)
    <br/><br/><b>Examples:</b>
    <br/>yumpu.com,blog.yumpu.com,developers.yumpu.com
    <br/>yumpu.com
 * @apiParam {String} [validity] 	Valid from and / or valid until
    <br/><br/><b>Examples:</b>
    <br/>2013-10-01T00:00:00-2013-10-30T23:59:59 (valid from 2013-10-01 00:00:00, valid until 2013-10-30 23:59:59)
    <br/>2013-10-01T00:00:00- (valid from 2013-10-01 00:00:00-)
    </br>-2013-10-30T23:59:59 (valid until -2013-10-30 23:59:59)
 * @apiParam {String} [blurred] 	Page numbers seperated by comma.
    <br/><br/><b>Examples:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_image] Image data
    <br/>The image must be less than 2 MB in size.
    <br/>Allowed mime types are image/gif, image/jpeg, image/pjpeg, image/png and image/x-png.
    <br/>The image will be resized to fit in the page dimensions (of your magazine).
    <br/><br/><b>Note:</b> If you use page_teaser_image, the parameters page_teaser_page_range and page_teaser_url are required.
 * @apiParam {String} [page_teaser_page_range] Page numbers seperated by comma.
    <br/><br/><b>Example:</b> 1-2, 5-9, 11-
 * @apiParam {String} [page_teaser_page_range] A valid URL.
    <br/><br/><b>Example:</b> http://www.yumpu.com/en
 * @apiParam {String} [downloadable] Allow users to download your source pdf file. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [detect_elements] Detect elements automatically? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [recommended_magazines] Show recommended magazines on Yumpu? y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [social_sharing] Show social sharing buttons on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_social_sharing] Show social sharing buttons in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_download_pdf] Show button „download pdf“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_print_page] Show button „print page“ in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_branding] Show Yumpu branding in Yumpu Player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_sidebar] Show a list of recommended documents in Yumpu Player. y or n
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [player_html5_c2r]	Activate HTML5 full screen on Yumpu. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_outer_shadow] Drop shadow in Yumpu player. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_inner_shadow] Shadow effects on pages. y or n
    <br/><br/><b>Default:</b> y
 * @apiParam {String} [player_ga] Activate Google Analytics tracking. A valid UA code from Google Analytics.
 * @apiParam {String} [access_tags] One or multiple access_tag ids (myid1 or myid1,myid2)
 * @apiParam {String} [subscriptions] One or multiple subscription ids (myid1 or myid1,myid2)
 * @apiParam {String} [iap] Enable In-App Purchase (y or n)
    <br/><br/><b>Default:</b> n
 * @apiParam {String} [itc_product_id] iTunes Product ID
 *
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
      "document": [
        {
          "id": "20582984",
          "url": "http://www.yumpu.com/en/document/view/20582984/my-new-document-title",
          "short_url": "http://www.yumpu.com/s/ynk9ahXBcnbAQ855",
          "image": {
            "small": "http://images001.yumpu.com/yumpu.com/000/020/462/612/1380545127_2485/thumb/Service_Animals000001.jpg",
            "medium": "http://images001.yumpu.com/yumpu.com/000/020/462/612/1380545127_2485/small/Service_Animals000001.jpg",
            "big": "http://images001.yumpu.com/yumpu.com/000/020/462/612/1380545127_2485/zoom/Service_Animals000001.jpg"
          },
          "language": "en",
          "title": "My new document title",
          "description": "This is a description for my document 2",
          "tags": [
            "autos",
            "flugzeug",
            "airbus",
            "airberlin"
          ],
          "embed_code": "iframe"
        }
      ],
      "state": "success"
    }
 *
 */
var parameters = {
    id: '20582984',
    title: 'Sieg'
};
// y.putDocument(parameters, function(statusCode, document){
//   console.log('Status: ' + statusCode)
//   console.log(document);
// });


/**
 * @api {delete} http://api.yumpu.com/2.0/document.json deleteDocument()
 * @apiVersion 1.0.0
 * @apiName Document delete
 * @apiGroup Document
 *
 *
 * @apiHeaderExample {js} Java-Script-Example:
 *  var yumpu = require('yumpu.js');
 *  var parameters = '{
 *    id: 20327033
 *  }';
 *  yumpu.deleteDocument(parameters, function(statusCode, document){
 *     console.log('Status: ' + statusCode);
 *     console.log(document);
 *  });
 *
 * @apiParam {Integer} id One of your document ids
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *    {"state":"success"}
 *
 */
var parameters = {
    id: 55886776,
  };
// y.deleteDocument(parameters, function(statusCode, document) {
//     console.log('Status: ' + statusCode)
//     console.log(document);
// });
